// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"skin-pro-app/internal/app"
	"skin-pro-app/internal/config"
	"skin-pro-app/internal/handler"
	"skin-pro-app/internal/repository"
	"skin-pro-app/internal/service"
)

// Injectors from wire.go:

func InitUserRouter(pool *pgxpool.Pool, cfg *config.GlobalConfig) app.UserRouter {
	userRepository := repository.NewUserRepository(pool)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	userRouter := app.NewUserRouter(userHandler, cfg)
	return userRouter
}

func InitAuthRouter(pool *pgxpool.Pool, cfg *config.GlobalConfig) app.AuthRouter {
	userRepository := repository.NewUserRepository(pool)
	userTokenRepository := repository.NewUserTokenRepository(pool)
	authService := service.NewAuthService(userRepository, userTokenRepository, cfg)
	userService := service.NewUserService(userRepository)
	authHandler := handler.NewAuthHandler(authService, userService)
	authRouter := app.NewAuthRouter(authHandler)
	return authRouter
}

func InitRouter(pool *pgxpool.Pool, cfg *config.GlobalConfig) *chi.Mux {
	userRouter := InitUserRouter(pool, cfg)
	authRouter := InitAuthRouter(pool, cfg)
	mux := app.NewRouter(userRouter, authRouter)
	return mux
}
