apiVersion: batch/v1
kind: Job
metadata:
  name: skin-pro-migrations
spec:
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: skinpro/skin-pro-backend:latest
          command: ["./myapp", "migrate"]
          workingDir: /app
          volumeMounts:
            - name: app-properties
              mountPath: /app/.env
              subPath: .env
              readOnly: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: app-properties
          secret:
            secretName: app-properties
            items:
              - key: .env
                path: .env
